import { parse } from 'yaml';
import { promises as fs } from 'fs';
import { join } from 'path';
import fetch from './network/fetch-wrapper';

const run = async () => {
  const response = await fetch('https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml');
  const data = parse(await response.text());
  const result = Object.entries(data as Record<string, { color?: string}>)
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    .filter(([_, o]) => (o).color)
    .reduce((colors, [language, { color }]) => ({
      ...colors,
      [language.toLowerCase()]: color?.toLowerCase()
    }), {});

  await fs.writeFile(join(__dirname, 'language-colors.ts'), `// This file is autogenerated! Do not modify!
// Run \`npm run update-language-colors\` to update this file.
export default ${JSON.stringify(result, null, 2)} as const;
`, 'utf-8');

  // eslint-disable-next-line no-console
  console.log(`Wrote ${join(__dirname, 'language-colors.ts')}`);
};

run();
